after_success: npm run coveralls
before_install:
  - git config --global user.name travis
  - git config --global user.email travis@locahost
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - '4.2'
  - 'stable'
os:
  - linux
sudo: false
