addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
before_install:
  - export CC="/usr/bin/gcc-4.9"
  - export CXX="/usr/bin/g++-4.9"
  - git config --global user.name travis
  - git config --global user.email travis@locahost
language: node_js
node_js:
  - '4.2'
  - 'stable'
os:
  - linux
sudo: false
